# class School(db.Model):
#     _tablename_ = 'school'
#     roll_number = db.Column(db.String(50), primary_key=True)
#     name = db.Column(db.String(50), nullable=False)
#     address1 = db.Column(db.String(50))
#     address2 = db.Column(db.String(50))
#     address3 = db.Column(db.String(50))
#     address4 = db.Column(db.String(50))
#     website = db.Column(db.String(50))
#     country = db.Column(db.String(50))
#     eircode = db.Column(db.String(50))
#     phone = db.Column(db.String(50))
#     email = db.Column(db.String(50))
#     principal_name = db.Column(db.String(50))
#     deis = db.Column(db.String(50))
#     school_gender = db.Column(db.String(50))
#     pupil_attendance_type = db.Column(db.String(50))
#     classification = db.Column(db.String(50))
#     gaeltacht_area_location = db.Column(db.String(50))
#     fee = db.Column(db.String(50))
#     religion = db.Column(db.String(50))
#     open_close_status = db.Column(db.String(50))
#     total_girl = db.Column(db.Integer)
#     total_boy = db.Column(db.Integer)
#     total_pupil = db.Column(db.Integer)
#     lat = db.Column(db.DECIMAL(10,5)) #??
#     lag = db.Column(db.DECIMAL(10,5))  #??
#     photo_ref1 = db.Column(db.String(255))
#     photo_ref2 = db.Column(db.String(255))
#     photo_ref3 = db.Column(db.String(255))
#     photo_ref4 = db.Column(db.String(255))
#     photo_ref5 = db.Column(db.String(255))
#     photo_ref6 = db.Column(db.String(255))
#     photo_ref7 = db.Column(db.String(255))
#     photo_ref8 = db.Column(db.String(255))
#     photo_ref9 = db.Column(db.String(255))
#     photo_ref10 = db.Column(db.String(255))
#
#     userlike = db.relationship('User_like', backref=db.backref('roll_number1'), lazy='dynamic')
#     history = db.relationship('History', backref=db.backref('roll_number2'), lazy='dynamic')
#     comments = db.relationship('Comments', backref=db.backref('roll_number3'), lazy='dynamic')
#     pro2015 = db.relationship('Pro2015', backref=db.backref('roll_number4'), lazy='select', uselist=False)
#     rank2017 = db.relationship('Rank2017', backref=db.backref('roll_number5'), lazy='select', uselist=False)